Srt:
  entry1:
  - 1
  - 1
  - 0
  entry2:
  - 2
  - 2
  - 1
  entry3:
  - 3
  - 2
  - 2
  entry4:
  - 4
  - 2
  - 3
  entry5:
  - 5
  - 2
  - 4
  entry6:
  - 6
  - 2
  - 5
  entry7:
  - 7
  - 2
  - 6
  nodeID: 1
aquasent:
  baudrate: 115200
  port: /dev/ttyUSB1
clientsocket:
  address: 192.168.2.101
  correlatethreadshort: 0.1
  cycleprefixms: 20
  gain: 0.01
  port: 80
  samplerate: 80000
drt:
  nodeID: 1
drtPlus:
  nodeID: 1
fskclient:
  address: 192.168.2.106
  correlatethreadshort: 0.1
  cycleprefixms: 20
  gain: 0.2
  port: 80
  readcycle: 30
  samplerate: 80000
  transmitAmp: 0.005
fsknewclient:
  address: 192.168.2.101
  correlatethreadshort: 0.1
  cycleprefixms: 20
  datasize: 84
  gain: 0.4
  port: 80
  readcycle: 30
  samplerate: 80000
  transmitAmp: 0.005
  upError: 0
newAloha:
  MacId: 1
  MinReSendTime: 8
  ReSendTimeRange: 12
qpskclient:
  address: 192.168.2.101
  datasize: 239
  port: 80
  qpsknumchannel: 4
  readcycle: 30
  rxgain: 0.2
  samplerate: 96000
  threshold: 0.1
  txgain: 0.005
server:
  port: 9080
simulatechannel:
  address: 127.0.0.1
  port: 30001
test:
  othernodeID:
  - 7
  packetnum: 63
  seed: 8
  testmode: 0
  timeforhandshake: 10
  timeinterval:
  - 4
  - 5
trace:
  tracefile: A.log
  tracemode: 1
  tracepath: ./tracefile/
  tracetime: Wed_Nov__4_11_45_42_2020
udp:
  pos_x: 0
  pos_y: 0
  pos_z: 0
vbf:
  position:
  - 1
  - 1
  - 1
