Srt:
  entry1:
  - 1
  - 1
  - 1
  entry2:
  - 2
  - 2
  - 0
  entry3:
  - 3
  - 3
  - 1
  entry4:
  - 4
  - 3
  - 2
  entry5:
  - 5
  - 3
  - 3
  entry6:
  - 6
  - 3
  - 4
  entry7:
  - 7
  - 3
  - 5
  nodeID: 2
aquasent:
  baudrate: 115200
  port: /dev/ttyUSB1
clientsocket:
  address: 192.168.2.102
  correlatethreadshort: 0.1
  cycleprefixms: 20
  gain: 0.01
  port: 80
  samplerate: 80000
drt:
  nodeID: 1
drtPlus:
  nodeID: 1
fskclient:
  address: 192.168.2.102
  correlatethreadshort: 0.1
  cycleprefixms: 20
  gain: 0.2
  port: 80
  readcycle: 30
  samplerate: 80000
  transmitAmp: 0.005
fsknewclient:
  address: 192.168.2.102
  correlatethreadshort: 0.1
  cycleprefixms: 20
  datasize: 84
  gain: 0.4
  port: 80
  readcycle: 30
  samplerate: 80000
  transmitAmp: 0.005
  upError: 0
newAloha:
  MacId: 2
  MinReSendTime: 8
  ReSendTimeRange: 12
qpskclient:
  address: 192.168.2.104
  datasize: 239
  port: 80
  qpsknumchannel: 4
  readcycle: 30
  rxgain: 0.2
  samplerate: 96000
  threshold: 0.1
  txgain: 0.005
server:
  port: 9081
simulatechannel:
  address: 127.0.0.1
  port: 30001
test:
  othernodeID:
  - 2
  - 3
  - 4
  packetnum: 100
  seed: 10
  testmode: 0
  timeforhandshake: 20
  timeinterval:
  - 3
  - 8
trace:
  tracefile: B.log
  tracemode: 1
  tracepath: ./tracefile/
  tracetime: Fri_Oct_23_13_26_17_2020
udp:
  pos_x: 500
  pos_y: 500
  pos_z: 500
vbf:
  position:
  - 1
  - 1
  - 1
